services:
  server:
    build:
      context: ./server
      target: dev
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./server:/app
      - ${GLOBAL_FAVA_DIR}:/app/fava
    env_file:
      - .env
    environment:
      - FAVA_DIR=${FAVA_DIR}
    networks:
      - internal
  
  client:
    build:
      context: ./client
      target: dev
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${SERVER_ADDRESS}:${SERVER_PORT}
    networks:
      - internal

  fava_user1:
    image: yegle/fava
    ports:
      - "${FAVA1_PORT}:5000"
    volumes:
      - ${GLOBAL_FAVA_DIR}/${USER_1_NAME}:/bean
    environment:
      - BEANCOUNT_FILE=/bean/ledger.beancount
    networks:
      - internal

  fava_user2:
    image: yegle/fava
    ports:
      - "${FAVA2_PORT}:5000"
    volumes:
      - ${GLOBAL_FAVA_DIR}/${USER_2_NAME}:/bean
    environment:
      - BEANCOUNT_FILE=/bean/ledger.beancount
    networks:
      - internal
    
networks:
  internal:
